linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - rowserrcheck
    - gosec
    - unconvert

skip-dirs:
  - build
  - vendor

