project_name: khelm
dist: ./build/dist
before:
  hooks:
  - go mod tidy
builds:
- main: ./cmd/khelm
  targets:
    - linux_amd64
    - linux_arm64
    - darwin_amd64
    - darwin_arm64
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -extldflags '-static' -X main.khelmVersion={{.Version}} -X main.helmVersion={{.Env.HELM_VERSION}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Version }}-dev-{{.ShortCommit}}'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs(\([^)]+\))?:'
    - '^test(\([^)]+\))?:'
    - '^chore(\([^)]+\))?:'
dockers:
- id: khelm-amd64-image
  image_templates:
  - mgoltzsche/khelm:{{.Version}}-amd64
  dockerfile: Dockerfile
  skip_push: true
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--build-arg=KHELM_VERSION={{.Version}}"
  - "--build-arg=HELM_VERSION={{.Env.HELM_VERSION}}"
  - "--platform=linux/amd64"
- id: khelm-arm64-image
  image_templates:
  - mgoltzsche/khelm:{{.Version}}-arm64v8
  dockerfile: Dockerfile
  goarch: arm64
  skip_push: true
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--build-arg=KHELM_VERSION={{.Version}}"
  - "--build-arg=HELM_VERSION={{.Env.HELM_VERSION}}"
  - "--platform=linux/arm64/v8"
docker_manifests:
- id: khelm-multiarch-latest-dockerhub-image
  name_template: docker.io/mgoltzsche/khelm:latest
  image_templates:
  - mgoltzsche/khelm:{{.Version}}-amd64
  - mgoltzsche/khelm:{{.Version}}-arm64v8
- id: khelm-multiarch-latest-ghcr-image
  name_template: ghcr.io/mgoltzsche/khelm:latest
  image_templates:
  - mgoltzsche/khelm:{{.Version}}-amd64
  - mgoltzsche/khelm:{{.Version}}-arm64v8
- id: khelm-multiarch-major-dockerhub-image
  name_template: docker.io/mgoltzsche/khelm:{{.Major}}
  image_templates:
  - mgoltzsche/khelm:{{.Version}}-amd64
  - mgoltzsche/khelm:{{.Version}}-arm64v8
- id: khelm-multiarch-major-ghcr-image
  name_template: ghcr.io/mgoltzsche/khelm:{{.Major}}
  image_templates:
  - mgoltzsche/khelm:{{.Version}}-amd64
  - mgoltzsche/khelm:{{.Version}}-arm64v8
- id: khelm-multiarch-dockerhub-image
  name_template: docker.io/mgoltzsche/khelm:{{.Version}}
  image_templates:
  - mgoltzsche/khelm:{{.Version}}-amd64
  - mgoltzsche/khelm:{{.Version}}-arm64v8
- id: khelm-multiarch-ghcr-image
  name_template: ghcr.io/mgoltzsche/khelm:{{.Version}}
  image_templates:
  - mgoltzsche/khelm:{{.Version}}-amd64
  - mgoltzsche/khelm:{{.Version}}-arm64v8
