apiVersion: v1
kind: ConfigMap
metadata:
  name: render-local-chart
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  # same structure as the generator.yaml within the other examples
  chart: /examples/kpt/local-chart/chart # chart must be mounted here
  name: myrelease
  namespace: mynamespace
  apiVersions:
  - myfancyapi/v1
  exclude:
  - apiVersion: v1
    kind: ConfigMap
    name: myconfiga
  # additional kpt function specific fields
  outputPath: output.yaml
  debug: true
